### ISSUE TITLE
sample for page without background blur

### ISSUE THREAD

**Issue by skunkwerk** [gradeup/google-one-tap-2.0#1]
How did you modify the HTML/CSS for the example with 'page without background blur'?
thanks for a great sample!

**Comment by AmanAgarwal041** [comment]
I will upload the example for the same

**Comment by AmanAgarwal041** [comment]
@skunkwerk added a sample for background blur. here's a [commit history](https://github.com/gradeup/google-one-tap-2.0/commit/b63bacc63d9eeba1c6b4596cd25037b1ae69c4fd) which you can refer to for the changes in the files.
